/**
 * Malaa Error Hub — Seed Dataset
 * 23 realistic bilingual error records spanning all 8 service domains and the 4 valid statuses:
 * - "not_reviewed"
 * - "in_review"
 * - "ready_for_engineering"
 * - "approved"
 */

var STATUS_CONFIG = {
  not_reviewed: {
    key: "not_reviewed",
    label: "Not Reviewed",
    badgeClass: "not_reviewed",
    description: "Request received and awaiting Product review."
  },
  in_review: {
    key: "in_review",
    label: "In Review",
    badgeClass: "in_review",
    description: "Product is reviewing or correcting the message."
  },
  ready_for_engineering: {
    key: "ready_for_engineering",
    label: "Ready for Engineering",
    badgeClass: "ready_for_engineering",
    description: "Product finalized the correction and it is waiting for Engineering implementation."
  },
  approved: {
    key: "approved",
    label: "Approved",
    badgeClass: "implemented",
    description: "Engineering implemented the correction and Product confirmed it."
  }
};

var SEED_ERRORS = [
  // --- 1. Auth Service ---
  {
    id: "auth_009",
    errorCode: "AUTH_009",
    service: "Auth Service",
    sourceReference: "apps/auth/src/validators/phone.ts:42",
    originalArMessage: "رقم الجوال المدخل غير صحيح",
    correctedArMessage: "رقم الهاتف غير صحيح. تحقق منه وحاول مرة أخرى.",
    originalEnMessage: "Phone number is not valid",
    correctedEnMessage: "The phone number is invalid. Check it and try again.",
    aiSuggestedTrigger: "User inputs a phone number that fails the regional format validator or regex check.",
    approvedTrigger: "User enters a phone number with invalid formatting or incorrect digit count during registration or login.",
    meaning: "The entered phone number does not conform to Saudi national or international dialing format.",
    customerSupportAction: "Ask the user to verify their phone number, ensure the country code (+966) is accurate, and try again.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "approved",
    saved: true
  },
  {
    id: "auth_013",
    errorCode: "AUTH_013",
    service: "Auth Service",
    sourceReference: "apps/auth/src/services/otp.ts:118",
    originalArMessage: "رمز التحقق غير صحيح",
    correctedArMessage: "رمز التحقق غير صحيح. تحقق منه وحاول مرة أخرى.",
    originalEnMessage: "Incorrect OTP entered",
    correctedEnMessage: "The OTP is incorrect. Check it and try again.",
    aiSuggestedTrigger: "Submitted OTP does not match the cached verification token in Redis.",
    approvedTrigger: "User submits an incorrect 4 or 6-digit OTP during two-factor authentication.",
    meaning: "The verification code entered does not match the active one-time password generated for the session.",
    customerSupportAction: "Ask the user to double-check their SMS inbox for the latest code received and re-enter it carefully.",
    customerSupportComment: "Customers often report confusing old OTP with the newly resent SMS code.",
    requestedField: "Both Arabic and English Messages",
    productResponse: "Approved clear wording to guide users to check their latest SMS.",
    status: "ready_for_engineering",
    saved: false
  },
  {
    id: "auth_018",
    errorCode: "AUTH_018",
    service: "Auth Service",
    sourceReference: "apps/auth/src/services/otp.ts:145",
    originalArMessage: "انتهت صلاحية الرمز",
    correctedArMessage: "انتهت صلاحية رمز التحقق. اطلب رمزًا جديدًا.",
    originalEnMessage: "OTP has expired",
    correctedEnMessage: "The OTP has expired. Request a new one.",
    aiSuggestedTrigger: "OTP TTL exceeds the 3-minute validity window before submission.",
    approvedTrigger: "The one-time verification password has expired after 180 seconds of inactivity.",
    meaning: "The verification code is no longer valid because the time limit expired before submission.",
    customerSupportAction: "Advise the user to tap 'Resend Code' on screen and enter the newly received code immediately.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "ready_for_engineering",
    saved: true
  },
  {
    id: "auth_046",
    errorCode: "AUTH_046",
    service: "Auth Service",
    sourceReference: "apps/auth/src/security/pin.ts:89",
    originalArMessage: "رمز الدخول خاطئ",
    correctedArMessage: "رمز الدخول غير صحيح. حاول مرة أخرى.",
    originalEnMessage: "Invalid PIN provided",
    correctedEnMessage: "The PIN is incorrect. Try again.",
    aiSuggestedTrigger: "Hashed PIN comparison fails against the user's stored credential hash.",
    approvedTrigger: "User enters an incorrect security PIN during app unlock or biometric fallback.",
    meaning: "The entered application PIN does not match the user's established security credentials.",
    customerSupportAction: "Ask the user to re-enter their PIN or use 'Forgot PIN' to initiate secure recovery if forgotten.",
    customerSupportComment: "Users ask how many attempts they have before lockout.",
    requestedField: "Arabic Message",
    productResponse: "",
    status: "not_reviewed",
    saved: false
  },

  // --- 2. Banks ---
  {
    id: "bank_011",
    errorCode: "BANK_011",
    service: "Banks",
    sourceReference: "services/bank-sync/src/adapters/open-banking.ts:204",
    originalArMessage: "فشل الاتصال بالبنك",
    correctedArMessage: "فشل في الاتصال بالبنك، الرجاء المحاولة لاحقاً",
    originalEnMessage: "Bank connection error",
    correctedEnMessage: "Failed connecting to the bank, please try again later",
    aiSuggestedTrigger: "Open banking aggregator API returns 504 Gateway Timeout or handshake failure.",
    approvedTrigger: "The app attempts to connect to the user's bank, but the bank service is unavailable or times out.",
    meaning: "The application could not establish a secure connection with the user's selected financial institution.",
    customerSupportAction: "Ask the user to wait a few minutes and retry. If unresolved, verify the specific bank and check open banking status.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "approved",
    saved: true
  },
  {
    id: "bank_024",
    errorCode: "BANK_024",
    service: "Banks",
    sourceReference: "services/bank-sync/src/sync/accounts.ts:77",
    originalArMessage: "الحساب البنكي غير نشط حاليا",
    correctedArMessage: "الحساب البنكي غير نشط، يرجى مراجعة البنك لتفعيله",
    originalEnMessage: "Account status dormant",
    correctedEnMessage: "Bank account is inactive, please contact your bank to activate it",
    aiSuggestedTrigger: "Open banking payload indicates account status is 'DORMANT' or 'BLOCKED'.",
    approvedTrigger: "User attempts to link or sync a bank account that is marked as inactive or frozen by their bank.",
    meaning: "The linked bank account cannot be debited or synchronized because its status is inactive at the source institution.",
    customerSupportAction: "Instruct the customer to log in to their banking portal or visit their branch to unfreeze the account.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "in_review",
    saved: false
  },
  {
    id: "bank_033",
    errorCode: "BANK_033",
    service: "Banks",
    sourceReference: "services/bank-sync/src/auth/consent.ts:132",
    originalArMessage: "انتهت فترة تفويض مشاركة البيانات البنكية",
    correctedArMessage: "انتهت صلاحية تفويض الربط البنكي. يرجى إعادة التفويض للمتابعة.",
    originalEnMessage: "Consent expired for bank connection",
    correctedEnMessage: "Bank connection consent has expired. Please renew authorization to continue.",
    aiSuggestedTrigger: "Open banking consent timestamp is older than regulatory max age (90 days).",
    approvedTrigger: "The 90-day Open Banking regulatory consent has expired and requires explicit customer re-authorization.",
    meaning: "The mandatory consent window granted by the user to access account data has expired under SAMA Open Banking framework.",
    customerSupportAction: "Guide the user to the Linked Accounts tab in Malaa app and click 'Renew Authorization' via their bank portal.",
    customerSupportComment: "The word 'تفويض' was confusing to some users; suggested 'إعادة ربط الحساب'.",
    requestedField: "Arabic Message",
    productResponse: "Reviewing SAMA regulatory terminology compatibility.",
    status: "in_review",
    saved: false
  },

  // --- 3. Custodian ---
  {
    id: "cst_011",
    errorCode: "CST_011",
    service: "Custodian",
    sourceReference: "services/custody/src/transactions/settlement.ts:312",
    originalArMessage: "تعذر تنفيذ طلب السحب حالياً",
    correctedArMessage: "تعذر تنفيذ طلب السحب، يرجى المحاولة مرة أخرى",
    originalEnMessage: "Unable to process withdrawal action",
    correctedEnMessage: "We couldn't process your withdrawal request. Please try again.",
    aiSuggestedTrigger: "Custody engine rejects withdrawal request because portfolio settlement is in pending clearance state.",
    approvedTrigger: "The user attempts to perform a withdrawal or related transaction while its current status is not eligible for that action.",
    meaning: "The requested action cannot be completed because the current transaction or withdrawal status does not allow it.",
    customerSupportAction: "Ask the user to retry the withdrawal. If the issue continues, check whether the transaction or portfolio is in trade settlement.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "approved",
    saved: false
  },
  {
    id: "cst_022",
    errorCode: "CST_022",
    service: "Custodian",
    sourceReference: "services/custody/src/reconciliation/securities.ts:95",
    originalArMessage: "فشل التحقق من ملكية المحفظة الاستثمارية",
    correctedArMessage: "",
    originalEnMessage: "Custodian portfolio validation failed",
    correctedEnMessage: "",
    aiSuggestedTrigger: "NIN/Iqama number mismatch between user profile and custodian brokerage account registry.",
    approvedTrigger: "",
    meaning: "",
    customerSupportAction: "",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "not_reviewed",
    saved: false
  },

  // --- 4. Investment ---
  {
    id: "inv_018",
    errorCode: "INV_018",
    service: "Investment",
    sourceReference: "services/investments/src/kyc/onboarding.ts:167",
    originalArMessage: "بيانات العميل غير مكتملة للمتابعة",
    correctedArMessage: "لم يكتمل التحقق من هويتك، يرجى استكمال بياناتك للمتابعة",
    originalEnMessage: "User Missing KYC Data",
    correctedEnMessage: "Your identity verification is incomplete. Please complete your details to continue.",
    aiSuggestedTrigger: "User reaches investment onboarding risk profile step with incomplete national address or employment info.",
    approvedTrigger: "The error appears when the user reaches the identity verification step but has not completed all required information.",
    meaning: "The user's identity verification cannot continue because some required KYC information is missing or incomplete.",
    customerSupportAction: "Ask the user to return to the identity verification page and complete the missing required information.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "approved",
    saved: true
  },
  {
    id: "inv_026",
    errorCode: "INV_026",
    service: "Investment",
    sourceReference: "services/investments/src/withdrawals/validator.ts:88",
    originalArMessage: "الرصيد المتاح غير كافي للسحب",
    correctedArMessage: "مبلغ السحب غير كافي",
    originalEnMessage: "Insufficient withdrawable balance",
    correctedEnMessage: "Insufficient Withdraw Amount",
    aiSuggestedTrigger: "Requested withdrawal amount is greater than the unencumbered cash balance in the investment wallet.",
    approvedTrigger: "The user attempts to withdraw an amount greater than the currently available withdrawable amount.",
    meaning: "The requested withdrawal amount is not available for withdrawal.",
    customerSupportAction: "Ask the user to check the available withdrawable amount and retry using an amount within the available balance.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "ready_for_engineering",
    saved: false
  },
  {
    id: "inv_050",
    errorCode: "INV_050",
    service: "Investment",
    sourceReference: "services/investments/src/orders/market-hours.ts:44",
    originalArMessage: "السوق المالي مغلق حاليا، سيتم تنفيذ الأمر لاحقا",
    correctedArMessage: "السوق المالي مغلق، سيتم معالجة أمر الاستثمار في يوم العمل القادم",
    originalEnMessage: "Market closed, order queued",
    correctedEnMessage: "Financial market is closed. Your order will be processed on the next business day.",
    aiSuggestedTrigger: "Order submitted outside Tadawul or mutual fund trading hours (Sunday-Thursday 10:00-15:00).",
    approvedTrigger: "User submits an investment deposit or rebalancing request outside active fund dealing cut-off hours.",
    meaning: "The investment order was recorded outside the operational market window and is queued for next business cycle.",
    customerSupportAction: "Inform the user that their order is safely queued and will execute automatically during the next fund valuation window.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "in_review",
    saved: false
  },

  // --- 5. Omnibus ---
  {
    id: "omn_011",
    errorCode: "OMN_011",
    service: "Omnibus",
    sourceReference: "services/omnibus/src/pooling/transfer.ts:182",
    originalArMessage: "فشلت عملية التحويل المجمع",
    correctedArMessage: "فشلت عملية الدفع",
    originalEnMessage: "Omnibus batch payment failed",
    correctedEnMessage: "The payment was failed",
    aiSuggestedTrigger: "Virtual IBAN escrow settlement engine encounters a bank transfer rejection code.",
    approvedTrigger: "A payment attempt is submitted but fails during payment processing.",
    meaning: "The payment could not be completed successfully.",
    customerSupportAction: "Ask the user to retry the payment. If the payment continues to fail, confirm the transaction details and escalate the issue if required.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "approved",
    saved: false
  },
  {
    id: "omn_025",
    errorCode: "OMN_025",
    service: "Omnibus",
    sourceReference: "services/omnibus/src/accounts/allocation.ts:91",
    originalArMessage: "الآيبان الافتراضي غير موجود بالنظام",
    correctedArMessage: "",
    originalEnMessage: "Virtual IBAN not found",
    correctedEnMessage: "",
    aiSuggestedTrigger: "Inbound SARIE transfer received with an unmatched virtual account identifier.",
    approvedTrigger: "",
    meaning: "",
    customerSupportAction: "",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "not_reviewed",
    saved: false
  },

  // --- 6. Payment Gateway ---
  {
    id: "pay_000",
    errorCode: "PAY_000",
    service: "Payment Gateway",
    sourceReference: "services/payments/src/gateways/apple-pay.ts:114",
    originalArMessage: "المبلغ غير متطابق مع الفاتورة",
    correctedArMessage: "المبلغ غير متطابق",
    originalEnMessage: "Payment mismatch with invoice",
    correctedEnMessage: "New payment mismatch amount",
    aiSuggestedTrigger: "Webhook payload payment amount differs from checkout session initialized amount.",
    approvedTrigger: "The payment amount received or processed does not match the expected payment amount.",
    meaning: "The payment amount does not match the amount expected by the payment process.",
    customerSupportAction: "Ask the user to retry the payment. If the issue continues, capture the relevant payment details and escalate the mismatch for investigation.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "ready_for_engineering",
    saved: false
  },
  {
    id: "pay_014",
    errorCode: "PAY_014",
    service: "Payment Gateway",
    sourceReference: "services/payments/src/gateways/mada.ts:253",
    originalArMessage: "تم رفض البطاقة بواسطة البنك المصدر",
    correctedArMessage: "تم رفض عملية الدفع من قبل البنك، يرجى مراجعة البنك المصدر للبطاقة",
    originalEnMessage: "Card declined by issuing bank",
    correctedEnMessage: "Payment was declined by your bank. Please check with your card issuer.",
    aiSuggestedTrigger: "Mada/Visa gateway response returns code '51: Insufficient funds' or '05: Do not honor'.",
    approvedTrigger: "The user's bank card issuer declined the payment authorization during 3D-Secure challenge.",
    meaning: "The payment transaction was rejected by the cardholder's issuing bank.",
    customerSupportAction: "Ask the customer to check their daily online transaction limits in their banking app or try another card.",
    customerSupportComment: "Please specify Mada card limits in English message.",
    requestedField: "English Message",
    productResponse: "",
    status: "not_reviewed",
    saved: false
  },
  {
    id: "pay_032",
    errorCode: "PAY_032",
    service: "Payment Gateway",
    sourceReference: "services/payments/src/security/3ds.ts:98",
    originalArMessage: "فشل التحقق الأمني ثلاثي الأبعاد",
    correctedArMessage: "لم يتم استكمال التحقق الأمني (3D Secure). الرجاء المحاولة مرة أخرى.",
    originalEnMessage: "3DS authentication timeout",
    correctedEnMessage: "3D Secure authentication was not completed. Please try again.",
    aiSuggestedTrigger: "User abandons OTP iframe or 3DS challenge timeout exceeds 120 seconds.",
    approvedTrigger: "The cardholder did not complete the 3D-Secure authentication prompt before the session timed out.",
    meaning: "The mandatory bank security verification code was not entered in time.",
    customerSupportAction: "Advise the user to ensure good mobile connectivity to receive their bank's 3D-Secure SMS code promptly.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "ready_for_engineering",
    saved: false
  },

  // --- 7. Malaa ---
  {
    id: "mal_001",
    errorCode: "MAL_001",
    service: "Malaa",
    sourceReference: "apps/mobile-api/src/pfm/budget.ts:162",
    originalArMessage: "فشل حفظ الميزانية الشهرية",
    correctedArMessage: "تعذر حفظ الميزانية، يرجى التحقق من القيم المدخلة والمحاولة لاحقاً",
    originalEnMessage: "Failed to save budget",
    correctedEnMessage: "Unable to save budget. Please check the entered amounts and try again.",
    aiSuggestedTrigger: "Budget category sum exceeds total monthly income limit or negative values passed.",
    approvedTrigger: "User submits monthly budget allocation with invalid numerical constraints.",
    meaning: "The personal financial management (PFM) budget could not be persisted due to validation errors.",
    customerSupportAction: "Guide the user to verify that category limits are positive integers and do not exceed monthly limits.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "approved",
    saved: false
  },
  {
    id: "mal_015",
    errorCode: "MAL_015",
    service: "Malaa",
    sourceReference: "apps/mobile-api/src/categorization/rules.ts:74",
    originalArMessage: "قاعدة التصنيف التلقائي موجودة مسبقاً",
    correctedArMessage: "قاعدة التصنيف الذكي موجودة مسبقاً لهذه المعاملة",
    originalEnMessage: "Auto categorization rule already exists",
    correctedEnMessage: "Smart categorization rule already exists for this merchant",
    aiSuggestedTrigger: "Merchant regex duplicate key collision when creating a custom PFM rule.",
    approvedTrigger: "User creates a transaction categorization rule for a merchant that already has an identical active rule.",
    meaning: "A custom auto-categorization rule already exists with identical merchant matching criteria.",
    customerSupportAction: "Inform the user that transactions for this merchant are already auto-categorized under their existing rules.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "in_review",
    saved: false
  },
  {
    id: "mal_029",
    errorCode: "MAL_029",
    service: "Malaa",
    sourceReference: "apps/mobile-api/src/sync/insights.ts:210",
    originalArMessage: "البيانات المالية غير كافية لإنشاء التقرير المالي",
    correctedArMessage: "",
    originalEnMessage: "Insufficient financial data for analytics",
    correctedEnMessage: "",
    aiSuggestedTrigger: "Account transaction history contains fewer than 5 records across the last 30 days.",
    approvedTrigger: "",
    meaning: "",
    customerSupportAction: "",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "not_reviewed",
    saved: false
  },

  // --- 8. Lending ---
  {
    id: "lnd_002",
    errorCode: "LND_002",
    service: "Lending",
    sourceReference: "services/lending/src/eligibility/simah.ts:188",
    originalArMessage: "فشل الاستعلام من سمة",
    correctedArMessage: "تعذر التحقق من السجل الائتماني حالياً، يرجى المحاولة لاحقاً",
    originalEnMessage: "SIMAH credit bureau query failed",
    correctedEnMessage: "Unable to verify credit record with SIMAH right now. Please try again later.",
    aiSuggestedTrigger: "SIMAH credit score API service returns network timeout or 503 Service Unavailable.",
    approvedTrigger: "The credit line engine was unable to complete the real-time SIMAH bureau inquiry.",
    meaning: "Temporary connectivity issue with the national credit rating agency (SIMAH) during credit line check.",
    customerSupportAction: "Advise user to wait 15 minutes and re-apply. Check internal ops dashboard for SIMAH service alerts.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "approved",
    saved: true
  },
  {
    id: "lnd_019",
    errorCode: "LND_019",
    service: "Lending",
    sourceReference: "services/lending/src/contracts/nafath.ts:145",
    originalArMessage: "فشل توقيع العقد الرقمي عبر نفاذ",
    correctedArMessage: "لم يتم تأكيد التوقيع الرقمي للعقد عبر نفاذ في الوقت المحدد",
    originalEnMessage: "Nafath digital contract signature expired",
    correctedEnMessage: "Nafath digital contract signing timed out. Please initiate a new request.",
    aiSuggestedTrigger: "Nafath push notification approval expired without biometric confirmation from user.",
    approvedTrigger: "The user did not accept the Nafath digital contract verification push within the 180-second window.",
    meaning: "The digital lending contract signature could not be verified via Nafath national identity portal.",
    customerSupportAction: "Guide the user to restart the digital signature step and accept the prompt in the Nafath app immediately.",
    customerSupportComment: "",
    requestedField: "",
    productResponse: "",
    status: "ready_for_engineering",
    saved: false
  },
  {
    id: "lnd_041",
    errorCode: "LND_041",
    service: "Lending",
    sourceReference: "services/lending/src/repayment/schedule.ts:89",
    originalArMessage: "تاريخ السداد المختار غير متاح",
    correctedArMessage: "يجب أن يتوافق تاريخ السداد الشهري مع موعد إيداع الراتب",
    originalEnMessage: "Repayment date invalid",
    correctedEnMessage: "Monthly repayment date must align with your verified salary deposit date",
    aiSuggestedTrigger: "Selected monthly installment due date is more than 7 days from verified employer payroll date.",
    approvedTrigger: "The requested installment repayment day is outside the regulatory payroll window.",
    meaning: "The requested installment repayment day is outside the regulatory payroll window.",
    customerSupportAction: "Ask the customer to choose a repayment date between the 27th and 5th of the month.",
    customerSupportComment: "Borrowers need clarity on salary matching range.",
    requestedField: "Both Arabic and English Messages",
    productResponse: "",
    status: "not_reviewed",
    saved: false
  }
];

